### ISSUE TITLE
Workspace related functions on Databricks

### ISSUE THREAD

**Issue by JLSMforPYR** [Azure/azureml-sdk-for-r#196]
**Describe the bug**
I am trying to use this library in Databricks and I encounter a problem in the operation of this function (it hangs). 

**To Reproduce**

- install the azureml sdk in this way so that databricks work on this enviroment
azuremlsdk::install_azureml(envname = "databricks-standard")

- Then I run 'get_current_run()' to check that it went well, and return:
<azureml.core.run._OfflineRun>

- None of the Azure Workspace related commands work

**Comment by ninghu** [comment]
Thanks for reporting this issue. 

It seems to get stuck at workspace interactive login step. Interactive login requires to open a web browser to finish the authentication but somehow it's not available. We had a similar issue with RStudio server before.

There is one workaround you can give a try which forces to use device code login. Run below code before calling any workspace related functions. See it helps.

```
webbrowser <- reticulate::import("webbrowser")
# this will force to use device code login
webbrowser$"_tryorder" <- list()
```

**Comment by JLSMforPYR** [comment]
Your approach does not work, but thanks anyway.
In case it may be helpful to you, currently I'm using the runtime 5.5 Conda Beta.

**Comment by ninghu** [comment]
Thanks for trying. I was able to repro your issue in a databricks R notebook.

The problem is databricks doesn't support real-time log streaming during the code execution when you are in the notebook. I found a workaround though.

1) Load workspace

```
existing_ws <- get_workspace(name = <workspace_name>, 
			     subscription_id = <subscription_id>, 
			     resource_group = <resource_group_name>)
```

2) Go to your cluster -> "Driver Logs" -> you should see some message like below. Follow the instructions to complete authenticate

> Performing interactive authentication. Please follow the instructions on the terminal.
> To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code BUR8WUX9Z to authenticate.

3) Open your notebook and run below code to verify other workspace operation is working

```
get_workspace_details(existing_ws)
```

**Comment by JLSMforPYR** [comment]
Works.
Thanks!
