### ISSUE TITLE
Attach an existing AKS Dev-test inference cluster

### ISSUE THREAD

**Issue by lucazav** [Azure/azureml-sdk-for-r#266]
I've created an Inference Cluster with Dev-test purpose via the web UI (I couldn't create it via SDK).
I'd like to reference it in order to deploy a model over it.
I tried using `attach_aks_compute` and `get_compute` with no success.
How can I reference it so that the following code will work?

```
aks_target <- ...(ws, cluster_name = "mycluster")

aks_config <- aks_webservice_deployment_config(cpu_cores = 1, memory_gb = 1)

aks_service <- deploy_model(ws, 
                            'test-aks', 
                            models = list(model), 
                            inference_config = inference_config, 
                            deployment_config = aks_config,
                            deployment_target = aks_target)
```

**Comment by lucazav** [comment]
I found the following way to get the list of all the AKS compute targets:


`azureml$core$compute$aks$AksCompute$list(ws)`

So I can get the target I want (in this case the first) using this code:

`aks_target <- azureml$core$compute$aks$AksCompute$list(ws)[[1]]`

Then I deployed my model using it:

```
aks_service <- deploy_model(ws,
                            'my-cluster-aks', 
                            models = list(model), 
                            inference_config = inference_config, 
                            deployment_target = aks_target)

wait_for_deployment(aks_service, show_output = TRUE)
```

**Comment by mx-iao** [comment]
- Work item to expose `cluster_purpose` parameter to create devtest purpose cluster from SDK: #270 
- What is the error you are getting when you use `attach_aks_compute()`? Is it unable to find the compute based on the cluster name?

**Comment by lucazav** [comment]
I used the following code:

```
attach_aks_compute(ws, cluster_name = "my-cluster",
                   resource_group = "my-resource-group")
```

and I got the following error:

> cluster_name is not provided

**Comment by mx-iao** [comment]
We are investigating this issue. As a workaround, you can try to attach your cluster via the CLI. Refer to the "Using the CLI" section of this [documentation](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-deploy-azure-kubernetes-service#attach-an-existing-aks-cluster)

**Comment by mx-iao** [comment]
@lucazav Are you providing AKS resource by resourcegroup+cluster name, or by resource ID?

**Comment by lucazav** [comment]
@mx-iao as shown before I tried first with resource group + cluster name with no success ("cluster_name not provided") and then I tried with the `resource_id` with no success too ("Invalid resource_id provided: xxxxxxx").
I'm providing the Resource ID highlighed in the following picture:

![image](https://user-images.githubusercontent.com/6104437/76010706-a4ac6400-5f13-11ea-8b85-c2bace2ea95b.png)

Is it right?

**Comment by lucazav** [comment]
Just to clarify, I created the Dev-test AKS directly into the Workspace using the web UI. My aim is just to point to it as an AKS target (`aks_target`) to be used as following:

```
aks_service <- deploy_model(ws,
                            'test-dev-aks', 
                            models = list(model_2), 
                            inference_config = inference_config2, 
                            deployment_target = aks_target)
```

**Comment by mx-iao** [comment]
Hey @lucazav, I think I've figured out the issue.
A couple of things:
- If you create an AKS cluster in the studio UI (ml.azure.com) through Compute > Inference clusters > New (which is what you've done I believe), this means that you have already created the AKS cluster in your workspace. This is the equivalent of running `create_aks_cluster()` in the SDK. However, if you had an existing AKS cluster that was not created in the context of your AML workspace, for example if you had created it through the [Azure portal](https://docs.microsoft.com/en-us/azure/aks/kubernetes-walkthrough-portal), then you would have to attach it with `attach_aks_compute()`
- Since the cluster is already in your workspace, you should be able to use `get_compute()` with the name as whatever is specified in the "Compute name" section of the compute details Attributes view. If this is giving you an issue that should not be the case, so let us know what the error you're getting is.
- There is actually a bug in our `attach_aks_compute()` method, so even though you shouldn't be using it in this scenario thanks for catching it. We will open a PR for that fix.

**Comment by lucazav** [comment]
Hi @mx-iao ,

that was my feeling: my AKS cluster was already attached. May be a simple return message like "_The 'you-cluster-name' AKS cluster is already attached_" should be a good output of the `attach_aks_compute()` in this case.
I tried the `get_compute()` function as you suggested and all works fine.

We definitely need a complete documentation about how to do these simple operations :)
