### ISSUE TITLE
Inference function as Webservice

### ISSUE THREAD

**Issue by VincentTennanty** [Azure/azureml-sdk-for-r#280]
Hi all
I have created my workflow right through to submitting an experiment.
My tsoutliers code detects outliers.

While trying to deploy as a  webservice I came up against an example of predict in the config entry script.
But Im trying to infer. i.e Trying to look back and detect outliers in data rather than predict.
Is there any documentation around deploying Inference functions as a webservice?

**Comment by VincentTennanty** [comment]
Just in case Im not clear or wrong.. I basically have a model that detects outliers. Im trying to use this model to return a results dataset.  Im trying to deploy the model into a webservice. To deploy into the webservice, inference config script needs to call my model. The code examples are based on predict() however I just want to use my model to return a results dataset of values from today backwards in time. I almost want to call Predict minus x days if thats possible.  Or can predict return past data?

<img width="595" alt="Screenshot 2020-03-11 at 21 42 48" src="https://user-images.githubusercontent.com/62069656/76467754-3881a280-63e2-11ea-930f-c1e8f6f7d65b.png">

**Comment by mx-iao** [comment]
Hi @VincentTennanty,
See this [documentation](https://azure.github.io/azureml-sdk-for-r/reference/inference_config.html#defining-the-entry-script) for more information.

In the examples, the models are created from using the caret package, so that is where the use of the predict function comes from. Azure ML does not require you to use any specific predict methods.

The entry script must contain an `init()` method that loads your model (which needs to be registered) and then returns a function that uses the model to make a prediction (or perform whatever logic you want) based on the input data passed to the function. Azure ML runs the init() method once, when the Docker container for your web service is started. The function returned by init() will be run every time the service is invoked to make a prediction (or whatever logic you've provided) on some input data. The inputs and outputs of this prediction function typically use JSON for serialization and deserialization.

The expectation of the entry script:
```
init <- function()
{
  # code to load your registered model
  
  function(data)
  {
    # the input data is passed to the service in the `data` parameter, typically JSON serialized
    # deserialize data into the format expected by your model, e.g. data.table
    # code for using your model with the input data to return the results that you want
    # serialize the results and return from the function
  }
}
```

**Comment by VincentTennanty** [comment]
Hi @mx-iao .
Im still having trouble.
Basically when I try deploy as a web service , when i view getwebservice_logs(mywebservicename),
My error says Init function not found, further down the error I see Entry_script not found.

With regards the Init function, would you mind taking a look.
![Screenshot 2020-03-19 at 15 35 51](https://user-images.githubusercontent.com/62069656/77084919-7ccefd00-69f7-11ea-977c-c82cb9fe8e21.png)

Im either not serializing properly or using my model properly.
Many thanks

**Comment by mx-iao** [comment]
Closing, please reopen if needed.
