### ISSUE TITLE
get_dataset_by_name() throws error

### ISSUE THREAD

**Issue by mx-iao** [Azure/azureml-sdk-for-r#281]
Customer is reporting the following error:
```
> library(azuremlsdk)
> ws <- load_workspace_from_config()
> dataset <- get_dataset_by_name(ws, name="IBM HR Analytics Employee Attrition and Performance", version = "latest")
Error in .Call(`_reticulate_py_str_impl`, x) : reached elapsed time limit
```
With v 0.6.85 of the R SDK

Customer is also getting this error:
```
Error in py_get_attr_impl(x, name, silent) : 
  AttributeError: module 'azureml.data' has no attribute 'abstract_dataset'
```

**Comment by mx-iao** [comment]
Customer is also getting this error:
```
Error in py_get_attr_impl(x, name, silent) : 
  AttributeError: module 'azureml.data' has no attribute 'abstract_dataset'
```

**Comment by tiagoh** [comment]
Same issue here

**Comment by csiebler** [comment]
As a workaround, this seems to be running well in Jupyter using a R kernel.

**Comment by diondrapeck** [comment]
**Update**

1. The issue has been isolated to RStudio (server and desktop), so as @csiebler mentioned, Jupyter with an R Kernel and R command line should both work without triggering the error.
2. The `Error in .Call(_reticulate_py_str_impl, x) : reached elapsed time limit` message does not prevent the creation of the dataset object. Thus, the functions still work in RStudio, despite the error. You should be able to continue your dataset workflow ignoring the message.
3. I will update this thread again with more details on a fix when we have them.

 

1.

**Comment by mx-iao** [comment]
Hi @csiebler & @tiagoh 

Can you try updating the underlying Python SDK and see if that resolves the error you are seeing?
Running `azuremlsdk::install_azureml(version = "1.1.5.1")` should work

We were able to get a more detailed error message during further testing:
"WARNING - Found installed version of "azureml-dataprep": 1.1.1Minimum supported version: 1.1.29
Some functionality may not work correctly. Please upgrade by running:
pip install azureml-dataprep[fuse,pandas] --upgrade
Error in .Call(`_reticulate_py_str_impl`, x) : reached elapsed time limit"

It's possible that this version check was somehow leading to the time out in RStudio. With the latest release of the Python SDK last week, azureml-dataprep will now be installed as part of the core SDK, so that check should have gone away with the new version. Please let us know if you're still seeing the same issue.

**Comment by csiebler** [comment]
Hi @mx-iao,

I'ved tried running:

`azuremlsdk::install_azureml(version = "1.1.5.1")`

I assume R Studio on Compute Instance uses the following env:

```
$ conda activate /home/azureuser/.local/share/r-miniconda/envs/r-reticulate
$ pip freeze | grep azureml-core
azureml-core==1.1.5.5
```

So that seemed to have worked. But when I run the code, I still get the error:

```
> library(azuremlsdk)
> ws <- load_workspace_from_config()
> dataset <- get_dataset_by_name(ws, name="IBM HR Analytics Employee Attrition and Performance", version = "latest")
Error in .Call(`_reticulate_py_str_impl`, x) : reached elapsed time limit
```

**Comment by zackarno** [comment]
Hi All,

I realize this might seem a bit random, but we are running into this same strange error (`Error in .Call(_reticulate_py_str_impl, x) : reached elapsed time limit`) on an unrelated remote sensing project. We noticed the same main things about the error, a.) it "does not prevent the creation of the dataset object" (however, it does cause a considerable lag in execution/creation of object, b.) the code/functions run completely fine without any issue when using the standard `RGui` that comes with R rather than Rstudio.

Therefore, we think the issue is in Rstudio, but still trying to figure out the best next course of action and were wondering if anyone here (@diondrapeck , @csiebler , etc) ever figured out a.) a good solution, b.) what exactly the issue was that was causing the error?

Any suggestions/ideas you have on this would be greatly appreciated as we are finding it quite difficult to troubleshoot!

Thank you very much!
