### ISSUE TITLE
How to get Runs from an Experiment

### ISSUE THREAD

**Issue by lucazav** [Azure/azureml-sdk-for-r#334]
I'm trying to list all the runs in a given experiment in the following way:

```
runs <- get_runs_in_experiment(experiment = exp)
runs
```

I'm getting the following output:

> <generator object Run._rehydrate_runs at 0x7f8de9227660>

I expected a list of runs or something like that. How can i inspect the resulting runs? How can I then get, for example, the first run in `runs`?

**Comment by diondrapeck** [comment]
Hi Luca,

`get_runs_in_experiment` returns an iterator. Using reticulate, you can either get a list of all runs or get them sequentially. 

List of all runs:
`
runs <- get_runs_in_experiment(experiment = exp)
reticulate::iterate(runs)
`

nth run of all runs:
`
runs <- get_runs_in experiment(experiment = exp)
all_runs <- reticulate::iterate(runs)
all_runs[n]
`

Or you could call `reticulate::iter_next(runs)` to step through the list in order.

We'll have to evaluate how this function interacts with others in order to see if it makes sense to make this function automatically return a list.

**Comment by lucazav** [comment]
Thank you, @diondrapeck . It’d be really useful to add this code as an example in the help of the function
